### ISSUE TITLE
Error when invoking the sample command

### ISSUE THREAD

**Issue by ranelpadon** [mattn/vim-notification#3]
Installed the plugin via `vim-plug`. Then, tried running this in command mode:
`:call notification#show('Hello World')`

but there's an error and no popup is shown:
<img width="478" alt="Screen Shot 2022-07-30 at 8 16 52 AM" src="https://user-images.githubusercontent.com/4292088/181862631-3f763ec6-a3ea-48c3-ad16-0c520f2970ac.png">

Am I missing something? Thanks

**Comment by 4513ECHO** [comment]
What version of vim are you using? Could you tell me the full output of `:version`?

**Comment by Shougo** [comment]
`popup_create()` is added in Vim 8.1.1364+.
Your Vim version is too old or your Vim is neovim.

Note:  I think `vim-notification` should check the version though.

**Comment by ranelpadon** [comment]
@4513ECHO @Shougo I'm using **Neovim 0.6.1** (Jan 01, 2022 release):
```
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@Mac-1640963667289.local
```

Is this expected not to work in Neovim? Thanks

**Comment by Shougo** [comment]
vim-notification doesn't support neovim.
So it is expected.
You should use nvim-notify instead.

**Comment by ranelpadon** [comment]
@Shougo Ok will close this issue then. And thanks for recommending `nvim-notify`, realized that there are other Vim/Nvim notify plugins!
